services:
  web:
    container_name: "web-java"
    image: openjdk:17-jdk
    ports:
      - "80:8080"
    working_dir: "/app"
    volumes:
      - "./target:/app"
    command: "java -jar note-editor.jar"
    environment:
      DB_HOST: db:5432
    depends_on:
      - db

  db:
    image: postgres:12.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: note_editor
