spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST}/note_editor
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /docs