spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/note_editor
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /docs